# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: deploy-backend

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  t:
    name: Deploy docker image to server
    runs-on: ubuntu-latest
    steps:

      - name: Execute remote SSH cloudflared tunnel commands (rebuild)
        uses: npgy/cloudflared-ssh-action@v2.0
        with:    
          host: ${{ vars.SSH_IP }}
          username: ${{ vars.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          commands: |
            export DATABASE_CLIENT=${DATABASE_CLIENT}
            export DATABASE_URL=${DATABASE_URL}
            export DATABASE_HOST=${DATABASE_HOST}
            export DATABASE_PORT=${DATABASE_PORT}
            export DATABASE_NAME=${DATABASE_NAME}
            export DATABASE_USERNAME=${DATABASE_USERNAME}
            export DATABASE_PASSWORD=${DATABASE_PASSWORD}
            export SERVER_PORT=${SERVER_PORT}
            export JWT_SECRET=${JWT_SECRET}
            export TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
            export ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
            export API_TOKEN_SALT=${API_TOKEN_SALT}
            export APP_KEYS=${APP_KEYS}
            export PORT=${PORT}
            export HOST=${HOST}
            cd /srv/funds-ci
            git pull
            docker-compose pull backend
            docker-compose up -d backend
