name: Deploy backend
run-name: Deploy backend
on:
  repository_dispatch:
    types: deploy-backend
  
jobs:
  push_image:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.BACKEND_REPO }}
          token: ${{ secrets.BACKEND_REPO_PAT }}
          ref: 'staging'

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_URL }}/funds-backend:latest

  deploy_image:
    name: Deploy docker image to server
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute remote SSH cloudflared tunnel commands (rebuild)
        uses: npgy/cloudflared-ssh-action@v2.0
        with:    
          host: ${{ vars.SSH_IP }}
          username: ${{ vars.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          commands: |
            cd /srv/funds-ci
            docker-compose pull backend
            DATABASE_CLIENT=${{DATABASE_CLIENT:-mysql}}
            DATABASE_URL=${{DATABASE_URL}}
            DATABASE_HOST=${{DATABASE_HOST}}
            DATABASE_PORT=${{DATABASE_PORT:-3306}}
            DATABASE_NAME=${{DATABASE_NAME}}
            DATABASE_USERNAME=${{DATABASE_USERNAME}}
            DATABASE_PASSWORD=${{DATABASE_PASSWORD}}
            SERVER_PORT=${{SERVER_PORT}}
            JWT_SECRET=${{JWT_SECRET}}
            TRANSFER_TOKEN_SALT=${{TRANSFER_TOKEN_SALT}}
            ADMIN_JWT_SECRET=${{ADMIN_JWT_SECRET}}
            API_TOKEN_SALT=${{API_TOKEN_SALT}}
            APP_KEYS=${{APP_KEYS}}
            PORT=${{PORT:-1337}}
            HOST=${{HOST:-0.0.0.0}}
            docker-compose up -d backend
