name: Deploy backend
run-name: Deploy backend
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: deploy-backend
  
jobs:
  push_image:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.BACKEND_REPO }}
          token: ${{ secrets.BACKEND_REPO_PAT }}
          ref: 'staging'

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_URL }}/funds-backend:latest

  deploy_image:
    name: Deploy docker image to server
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute remote SSH cloudflared tunnel commands (rebuild)
        uses: npgy/cloudflared-ssh-action@v2.0
        with:    
          host: ${{ vars.SSH_IP }}
          username: ${{ vars.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          commands: |
            cd /srv/funds-ci
            docker-compose pull backend
            docker-compose up -d backend
        env:
          DATABASE_CLIENT=${{ vars.DATABASE_CLIENT || 'mysql' }}
          DATABASE_URL=${{ vars.DATABASE_URL }}
          DATABASE_HOST=${{ vars.DATABASE_HOST }}
          DATABASE_PORT=${{ vars.DATABASE_PORT || 3306 }}
          DATABASE_NAME=${{ vars.DATABASE_NAME }}
          DATABASE_USERNAME=${{ vars.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          SERVER_PORT=${{ vars.SERVER_PORT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          TRANSFER_TOKEN_SALT=${{ vars.TRANSFER_TOKEN_SALT }}
          ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
          API_TOKEN_SALT=${{ vars.API_TOKEN_SALT }}
          APP_KEYS=${{ vars.APP_KEYS }}
          PORT=${{ vars.PORT || 1337 }}
          HOST=${{ vars.HOST || '0.0.0.0' }}
