name: Deploy frontend

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: deploy-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.FRONTEND_REPO }}
          token: ${{ secrets.FRONTEND_REPO_PAT }}
          ref: 'staging'

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_URL }}/funds-frontend:latest

      - name: Execute remote SSH cloudflared tunnel commands (rebuild)
        uses: npgy/cloudflared-ssh-action@v2.0
        with:    
          host: ${{ vars.SSH_IP }}
          username: ${{ vars.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          commands: |          
            export SERVER_URL='${{ vars.SERVER_URL }}'

            cd /srv/funds-ci
            git pull
            docker-compose pull frontend
            docker-compose up -d frontend